### 1. Import Libraries

In [24]:
import pandas as pd 
import numpy as np
import os

### 2. Data Loading

In [25]:
import os
import pandas as pd

file_names = ["dien_thoai.csv", "may_tinh_bang.csv","laptop.csv", "dong_ho_thong_minh.csv"]

dataframes = []
categories = ["Điện thoại","Máy tính bảng", "Laptop", "Đồng hồ thông minh"]


dir = 'E:\MY CAREER\Internship Project\EDA\dataset\\tgdd\products'
for file_name, category in zip(file_names, categories):
    path = os.path.join(dir, file_name)
    try:
        df = pd.read_csv(path)
        df["category"] = category  # Thêm cột "category" với giá trị tương ứng
        dataframes.append(df)
    except pd.errors.ParserError as e:
        print(f"Error reading file {file_name}: {e}")

combined_df = pd.concat(dataframes, ignore_index=True)
combined_df.head()

,Unnamed: 0,id,title,link,description,box_price_present,box_price_old,box_price_percent,rating,cmt_count,category
0,0,303579.0,Điện thoại Samsung Galaxy A14 4GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung Galaxy A14 4GB là chiếc điện thoại mới...,3.890.000₫,4.490.000₫,-13%,4.2,219.0,Điện thoại
1,1,292770.0,Điện thoại Samsung Galaxy A14 6GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung tiếp tục chứng tỏ sự nỗ lực của mình t...,4.790.000₫,4.990.000₫,-4%,4.2,285.0,Điện thoại
2,2,299034.0,Điện thoại OPPO Find N2 Flip 5G,https://www.thegioididong.com/dtdd/oppo-find-n...,OPPO Find N2 Flip 5G - chiếc điện thoại gập đầ...,19.990.000₫,NaN,NaN,4.5,37.0,Điện thoại
3,3,251192.0,Điện thoại iPhone 14 Pro Max 128GB,https://www.thegioididong.com/dtdd/iphone-14-p...,iPhone 14 Pro Max một siêu phẩm trong giới sma...,\n <span>từ</span>\n ...,29.990.000₫,-11%,4.5,331.0,Điện thoại
4,4,289700.0,Điện thoại iPhone 14 Pro Max 256GB,https://www.thegioididong.com/dtdd/iphone-14-p...,Mới đây thì chiếc điện thoại iPhone 14 Pro Max...,\n <span>từ</span>\n ...,32.990.000₫,-10%,4.5,192.0,Điện thoại

In [26]:
combined_df.columns

Index(['Unnamed: 0', 'id', 'title', 'link', 'description', 'box_price_present',
       'box_price_old', 'box_price_percent', 'rating', 'cmt_count',
       'category'],
      dtype='object')

In [27]:
new_df = combined_df[['id', 'title', 'link', 'description', 'box_price_present',
       'box_price_old', 'box_price_percent', 'rating', 'cmt_count',
       'category']]
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 516 non-null    float64
 1   title              516 non-null    object
 2   link               542 non-null    object
 3   description        514 non-null    object
 4   box_price_present  497 non-null    object
 5   box_price_old      364 non-null    object
 6   box_price_percent  354 non-null    object
 7   rating             450 non-null    float64
 8   cmt_count          450 non-null    float64
 9   category           542 non-null    object
dtypes: float64(3), object(7)
memory usage: 42.5+ KB

### 3. Data Cleaning & Exploring

In [28]:
new_df.dropna(subset=['id'], inplace=True)

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\4039910416.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.dropna(subset=['id'], inplace=True)

Xóa các sản phẩm bị duplicated

In [29]:
new_df['id'].astype('int')
dup = new_df.duplicated(subset='id').sum()
dup

28

In [30]:
new_df.drop_duplicates(subset='id',inplace=True, keep='last')

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\2325118604.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop_duplicates(subset='id',inplace=True, keep='last')

In [31]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 488 entries, 0 to 541
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 488 non-null    float64
 1   title              488 non-null    object
 2   link               488 non-null    object
 3   description        486 non-null    object
 4   box_price_present  469 non-null    object
 5   box_price_old      350 non-null    object
 6   box_price_percent  340 non-null    object
 7   rating             423 non-null    float64
 8   cmt_count          423 non-null    float64
 9   category           488 non-null    object
dtypes: float64(3), object(7)
memory usage: 41.9+ KB

##### Handling missing value

Đối với giá có 2 có thể biểu hiện giá là 'box_price_present' biểu hiện giá sản phẩm hiện tại và 'box_price_old' biểu hiện giá sản phẩm trước đây (khi chưa áp dụng discount,...)
Có 2 TH có thể xảy ra:
+ Cả 2 cột này đều không có giá trị: Chỉ có thể xóa
+ Cột box_price_old thiếu thì dựa trên trường 'box_price_present'

In [32]:
new_df.dropna(subset=['box_price_present', 'box_price_old'], how='all', inplace=True)

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\4052192535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.dropna(subset=['box_price_present', 'box_price_old'], how='all', inplace=True)

In [33]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 469 entries, 0 to 541
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 469 non-null    float64
 1   title              469 non-null    object
 2   link               469 non-null    object
 3   description        467 non-null    object
 4   box_price_present  469 non-null    object
 5   box_price_old      350 non-null    object
 6   box_price_percent  340 non-null    object
 7   rating             406 non-null    float64
 8   cmt_count          406 non-null    float64
 9   category           469 non-null    object
dtypes: float64(3), object(7)
memory usage: 40.3+ KB

+ Chuẩn hóa giá về kiểu số
+ Điền các giá trị còn thiếu của 'box_price_old' là 0

In [35]:
def normalize_price(price):
    price = ''.join(c for c in price if c.isdigit() or c == ',')
    price = price.replace(',', '').replace('₫', '')
    try:
        price = int(price)
        return price
    except ValueError:
        return None
    

new_df['box_price_present'] = new_df['box_price_present'].apply(normalize_price)

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\656999878.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_present'] = new_df['box_price_present'].apply(normalize_price)

In [36]:
new_df['box_price_old'] = new_df['box_price_old'].str.replace('.', '')
new_df['box_price_old'] = new_df['box_price_old'].str.replace('₫', '')
new_df['box_price_old'].fillna(0,inplace=True)
new_df['box_price_old'] = new_df['box_price_old'].astype('int')

new_df

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\779291852.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  new_df['box_price_old'] = new_df['box_price_old'].str.replace('.', '')
C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\779291852.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_old'] = new_df['box_price_old'].str.replace('.', '')
C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\779291852.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_old'] = new_df['box_price_old'].str.replace('₫', '')
C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\779291852.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_old'].fillna(0,inplace=True)
C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\779291852.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_old'] = new_df['box_price_old'].astype('int')

,id,title,link,description,box_price_present,box_price_old,box_price_percent,rating,cmt_count,category
0,303579.0,Điện thoại Samsung Galaxy A14 4GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung Galaxy A14 4GB là chiếc điện thoại mới...,3890000,4490000,-13%,4.2,219.0,Điện thoại
1,292770.0,Điện thoại Samsung Galaxy A14 6GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung tiếp tục chứng tỏ sự nỗ lực của mình t...,4790000,4990000,-4%,4.2,285.0,Điện thoại
2,299034.0,Điện thoại OPPO Find N2 Flip 5G,https://www.thegioididong.com/dtdd/oppo-find-n...,OPPO Find N2 Flip 5G - chiếc điện thoại gập đầ...,19990000,0,NaN,4.5,37.0,Điện thoại
3,251192.0,Điện thoại iPhone 14 Pro Max 128GB,https://www.thegioididong.com/dtdd/iphone-14-p...,iPhone 14 Pro Max một siêu phẩm trong giới sma...,26590000,29990000,-11%,4.5,331.0,Điện thoại
4,289700.0,Điện thoại iPhone 14 Pro Max 256GB,https://www.thegioididong.com/dtdd/iphone-14-p...,Mới đây thì chiếc điện thoại iPhone 14 Pro Max...,29590000,32990000,-10%,4.5,192.0,Điện thoại
...,...,...,...,...,...,...,...,...,...,...
535,283903.0,Đồng hồ thông minh Amazfit Bip 3 Pro 44.12mm,https://www.thegioididong.com/dong-ho-thong-mi...,Amazfit Bip 3 Pro 44.12mm được thiết kế theo p...,990000,1390000,-28%,4.4,45.0,Đồng hồ thông minh
536,283146.0,Vòng đeo tay thông minh Mi Band 7 Đen,https://www.thegioididong.com/dong-ho-thong-mi...,"Tháng 5/2022, Xiaomi đã cho ra mắt thế hệ smar...",890000,1290000,-31%,4.5,140.0,Đồng hồ thông minh
537,283902.0,Đồng hồ thông minh Amazfit Bip 3 44.12mm,https://www.thegioididong.com/dong-ho-thong-mi...,"Tháng 6/2022, Huami đã cho ra mắt thế hệ tiếp ...",890000,1190000,-25%,4.5,81.0,Đồng hồ thông minh
538,286741.0,Đồng hồ thông minh HAYLOU RT2 45.7mm Đen,https://www.thegioididong.com/dong-ho-thong-mi...,HAYLOU RT2 mẫu đồng hồ thông minh ngon - bổ - ...,890000,1790000,-50%,4.3,103.0,Đồng hồ thông minh
541,286738.0,Đồng hồ thông minh HAYLOU GS 44.4mm Đen,https://www.thegioididong.com/dong-ho-thong-mi...,Đồng hồ thông minh HAYLOU GS thuộc phân khúc s...,690000,1390000,-50%,4.2,81.0,Đồng hồ thông minh

In [37]:
new_df['box_price_present'].isna().sum()

0

In [38]:
new_df['box_price_percent'] = new_df['box_price_percent'].str.replace('%','')
new_df['box_price_percent'] = pd.to_numeric(new_df['box_price_percent'], errors='coerce')

new_df['box_price_percent'].fillna(0, inplace=True)

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\1047102150.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_percent'] = new_df['box_price_percent'].str.replace('%','')
C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\1047102150.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_percent'] = pd.to_numeric(new_df['box_price_percent'], errors='coerce')
C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\1047102150.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['box_price_percent'].fillna(0, inplace=True)

In [39]:
new_df

,id,title,link,description,box_price_present,box_price_old,box_price_percent,rating,cmt_count,category
0,303579.0,Điện thoại Samsung Galaxy A14 4GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung Galaxy A14 4GB là chiếc điện thoại mới...,3890000,4490000,-13.0,4.2,219.0,Điện thoại
1,292770.0,Điện thoại Samsung Galaxy A14 6GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung tiếp tục chứng tỏ sự nỗ lực của mình t...,4790000,4990000,-4.0,4.2,285.0,Điện thoại
2,299034.0,Điện thoại OPPO Find N2 Flip 5G,https://www.thegioididong.com/dtdd/oppo-find-n...,OPPO Find N2 Flip 5G - chiếc điện thoại gập đầ...,19990000,0,0.0,4.5,37.0,Điện thoại
3,251192.0,Điện thoại iPhone 14 Pro Max 128GB,https://www.thegioididong.com/dtdd/iphone-14-p...,iPhone 14 Pro Max một siêu phẩm trong giới sma...,26590000,29990000,-11.0,4.5,331.0,Điện thoại
4,289700.0,Điện thoại iPhone 14 Pro Max 256GB,https://www.thegioididong.com/dtdd/iphone-14-p...,Mới đây thì chiếc điện thoại iPhone 14 Pro Max...,29590000,32990000,-10.0,4.5,192.0,Điện thoại
...,...,...,...,...,...,...,...,...,...,...
535,283903.0,Đồng hồ thông minh Amazfit Bip 3 Pro 44.12mm,https://www.thegioididong.com/dong-ho-thong-mi...,Amazfit Bip 3 Pro 44.12mm được thiết kế theo p...,990000,1390000,-28.0,4.4,45.0,Đồng hồ thông minh
536,283146.0,Vòng đeo tay thông minh Mi Band 7 Đen,https://www.thegioididong.com/dong-ho-thong-mi...,"Tháng 5/2022, Xiaomi đã cho ra mắt thế hệ smar...",890000,1290000,-31.0,4.5,140.0,Đồng hồ thông minh
537,283902.0,Đồng hồ thông minh Amazfit Bip 3 44.12mm,https://www.thegioididong.com/dong-ho-thong-mi...,"Tháng 6/2022, Huami đã cho ra mắt thế hệ tiếp ...",890000,1190000,-25.0,4.5,81.0,Đồng hồ thông minh
538,286741.0,Đồng hồ thông minh HAYLOU RT2 45.7mm Đen,https://www.thegioididong.com/dong-ho-thong-mi...,HAYLOU RT2 mẫu đồng hồ thông minh ngon - bổ - ...,890000,1790000,-50.0,4.3,103.0,Đồng hồ thông minh
541,286738.0,Đồng hồ thông minh HAYLOU GS 44.4mm Đen,https://www.thegioididong.com/dong-ho-thong-mi...,Đồng hồ thông minh HAYLOU GS thuộc phân khúc s...,690000,1390000,-50.0,4.2,81.0,Đồng hồ thông minh

In [40]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 469 entries, 0 to 541
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 469 non-null    float64
 1   title              469 non-null    object
 2   link               469 non-null    object
 3   description        467 non-null    object
 4   box_price_present  469 non-null    int64
 5   box_price_old      469 non-null    int32
 6   box_price_percent  469 non-null    float64
 7   rating             406 non-null    float64
 8   cmt_count          406 non-null    float64
 9   category           469 non-null    object
dtypes: float64(4), int32(1), int64(1), object(4)
memory usage: 38.5+ KB

In [41]:
zero_price_sum = new_df[new_df['box_price_old'] == 0]['box_price_old']
len(zero_price_sum)

119

In [42]:
zero_price_sum = new_df[new_df['box_price_percent'] == 0]['box_price_percent']
len(zero_price_sum)

129

In [43]:
mask = new_df['box_price_old'] == 0
new_df.loc[mask, 'box_price_old'] = new_df.loc[mask, 'box_price_present']

In [44]:
new_df['discount'] = ((new_df['box_price_old'] - new_df['box_price_present']) * 100/ new_df['box_price_old'])

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\1100367595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['discount'] = ((new_df['box_price_old'] - new_df['box_price_present']) * 100/ new_df['box_price_old'])

In [45]:
new_df['discount'] = new_df['discount'].astype('int')
new_df

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\1809678084.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['discount'] = new_df['discount'].astype('int')

,id,title,link,description,box_price_present,box_price_old,box_price_percent,rating,cmt_count,category,discount
0,303579.0,Điện thoại Samsung Galaxy A14 4GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung Galaxy A14 4GB là chiếc điện thoại mới...,3890000,4490000,-13.0,4.2,219.0,Điện thoại,13
1,292770.0,Điện thoại Samsung Galaxy A14 6GB,https://www.thegioididong.com/dtdd/samsung-gal...,Samsung tiếp tục chứng tỏ sự nỗ lực của mình t...,4790000,4990000,-4.0,4.2,285.0,Điện thoại,4
2,299034.0,Điện thoại OPPO Find N2 Flip 5G,https://www.thegioididong.com/dtdd/oppo-find-n...,OPPO Find N2 Flip 5G - chiếc điện thoại gập đầ...,19990000,19990000,0.0,4.5,37.0,Điện thoại,0
3,251192.0,Điện thoại iPhone 14 Pro Max 128GB,https://www.thegioididong.com/dtdd/iphone-14-p...,iPhone 14 Pro Max một siêu phẩm trong giới sma...,26590000,29990000,-11.0,4.5,331.0,Điện thoại,11
4,289700.0,Điện thoại iPhone 14 Pro Max 256GB,https://www.thegioididong.com/dtdd/iphone-14-p...,Mới đây thì chiếc điện thoại iPhone 14 Pro Max...,29590000,32990000,-10.0,4.5,192.0,Điện thoại,10
...,...,...,...,...,...,...,...,...,...,...,...
535,283903.0,Đồng hồ thông minh Amazfit Bip 3 Pro 44.12mm,https://www.thegioididong.com/dong-ho-thong-mi...,Amazfit Bip 3 Pro 44.12mm được thiết kế theo p...,990000,1390000,-28.0,4.4,45.0,Đồng hồ thông minh,28
536,283146.0,Vòng đeo tay thông minh Mi Band 7 Đen,https://www.thegioididong.com/dong-ho-thong-mi...,"Tháng 5/2022, Xiaomi đã cho ra mắt thế hệ smar...",890000,1290000,-31.0,4.5,140.0,Đồng hồ thông minh,31
537,283902.0,Đồng hồ thông minh Amazfit Bip 3 44.12mm,https://www.thegioididong.com/dong-ho-thong-mi...,"Tháng 6/2022, Huami đã cho ra mắt thế hệ tiếp ...",890000,1190000,-25.0,4.5,81.0,Đồng hồ thông minh,25
538,286741.0,Đồng hồ thông minh HAYLOU RT2 45.7mm Đen,https://www.thegioididong.com/dong-ho-thong-mi...,HAYLOU RT2 mẫu đồng hồ thông minh ngon - bổ - ...,890000,1790000,-50.0,4.3,103.0,Đồng hồ thông minh,50
541,286738.0,Đồng hồ thông minh HAYLOU GS 44.4mm Đen,https://www.thegioididong.com/dong-ho-thong-mi...,Đồng hồ thông minh HAYLOU GS thuộc phân khúc s...,690000,1390000,-50.0,4.2,81.0,Đồng hồ thông minh,50

In [46]:
new_df.drop('box_price_percent', axis=1, inplace=True)

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\842969135.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop('box_price_percent', axis=1, inplace=True)

In [47]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 469 entries, 0 to 541
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 469 non-null    float64
 1   title              469 non-null    object
 2   link               469 non-null    object
 3   description        467 non-null    object
 4   box_price_present  469 non-null    int64
 5   box_price_old      469 non-null    int64
 6   rating             406 non-null    float64
 7   cmt_count          406 non-null    float64
 8   category           469 non-null    object
 9   discount           469 non-null    int32
dtypes: float64(3), int32(1), int64(2), object(4)
memory usage: 38.5+ KB

In [48]:
new_df['cmt_count'].fillna(0,inplace=True)


new_df['rating'].fillna(0,inplace = True)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 469 entries, 0 to 541
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 469 non-null    float64
 1   title              469 non-null    object
 2   link               469 non-null    object
 3   description        467 non-null    object
 4   box_price_present  469 non-null    int64
 5   box_price_old      469 non-null    int64
 6   rating             469 non-null    float64
 7   cmt_count          469 non-null    float64
 8   category           469 non-null    object
 9   discount           469 non-null    int32
dtypes: float64(3), int32(1), int64(2), object(4)
memory usage: 38.5+ KB

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\1026339032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cmt_count'].fillna(0,inplace=True)
C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\1026339032.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['rating'].fillna(0,inplace = True)

In [49]:
new_df['cmt_count'] = new_df['cmt_count'].astype('int')

C:\Users\Rauciss\AppData\Local\Temp\ipykernel_14952\3634345584.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cmt_count'] = new_df['cmt_count'].astype('int')

In [50]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 469 entries, 0 to 541
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 469 non-null    float64
 1   title              469 non-null    object
 2   link               469 non-null    object
 3   description        467 non-null    object
 4   box_price_present  469 non-null    int64
 5   box_price_old      469 non-null    int64
 6   rating             469 non-null    float64
 7   cmt_count          469 non-null    int32
 8   category           469 non-null    object
 9   discount           469 non-null    int32
dtypes: float64(2), int32(2), int64(2), object(4)
memory usage: 36.6+ KB

In [51]:
new_df.to_csv('cleandata/tgdd_product.csv')